#!/bin/bash
g++ --std=c++14 -c -g -O0 -fno-inline-functions main.cpp -o main.o
g++ --std=c++14 -c -g -O0 -fno-inline-functions \
    test_MatrixGraphTraverser.cpp -o test_MatrixGraphTraverser.o
g++ -o bin/ex3 main.o test_MatrixGraphTraverser.o -lpthread


